# Generated by Django 5.0.6 on 2024-07-02 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('longitud', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ancho', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_suelo', models.CharField(choices=[('', 'Seleccione el tipo de suelo'), ('cesped_natural', 'Césped Natural'), ('cesped_artificial', 'Césped Artificial'), ('arcilla', 'Arcilla'), ('cemento', 'Cemento'), ('parquet', 'Parquet')], max_length=50)),
                ('tipo_red', models.CharField(choices=[('', 'Seleccione el tipo de red'), ('standard', 'Estándar'), ('reinforced', 'Reforzada')], max_length=50)),
                ('iluminacion', models.BooleanField(default=False)),
                ('marcador', models.BooleanField(default=False)),
                ('gradas', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeAgradecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField()),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sugerencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sugerencia', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('canchas', models.ManyToManyField(related_name='ventas', to='web.cancha')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cliente')),
            ],
        ),
    ]
