<<<<<<< HEAD
# Generated by Django 5.0.6 on 2024-05-28 13:53

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.0.6 on 2024-05-30 15:33

>>>>>>> ddc112c0a6b8a95e2adb1335bec8eb678052fa63
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> ddc112c0a6b8a95e2adb1335bec8eb678052fa63
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Cancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('precio_hora', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.cancha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.usuario')),
=======
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('dni', models.IntegerField(unique=True, verbose_name='DNI')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
>>>>>>> ddc112c0a6b8a95e2adb1335bec8eb678052fa63
            ],
        ),
    ]
