# Generated by Django 5.0.6 on 2024-06-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='cancha',
            new_name='canchas',
        ),
    ]
