# Generated by Django 5.0.6 on 2024-06-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_cancha_venta_canchas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='canchas',
        ),
        migrations.AddField(
            model_name='venta',
            name='canchas',
            field=models.ManyToManyField(to='web.cancha'),
        ),
    ]
