# Generated by Django 5.0.6 on 2024-07-02 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_mensajeagradecimiento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajeagradecimiento',
            old_name='fecha_creacion',
            new_name='fecha_envio',
        ),
        migrations.RemoveField(
            model_name='mensajeagradecimiento',
            name='mensaje',
        ),
        migrations.AddField(
            model_name='mensajeagradecimiento',
            name='contenido',
            field=models.TextField(default=datetime.datetime(2024, 7, 2, 18, 10, 5, 917045, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
